DROP TABLE IMAGE CASCADE CONSTRAINTS;
CREATE TABLE IMAGE(
    ID          VARCHAR2(32) PRIMARY KEY,
    URI         VARCHAR2(100) NOT NULL    
);

DROP SEQUENCE COLLECTION_SEQ;
CREATE SEQUENCE COLLECTION_SEQ
       INCREMENT BY 1
       START WITH 1;
DROP TABLE COLLECTION CASCADE CONSTRAINTS;
CREATE TABLE COLLECTION(
    ID           NUMBER          PRIMARY KEY,
    SEASON_CD    VARCHAR2(8)     NOT NULL,
    NAME         VARCHAR(100)    NOT NULL,
    THUMNAIL_ID  VARCHAR2(32) NOT NULL
);
ALTER TABLE COLLECTION ADD CONSTRAINT FK_COLLECTION_THUMNAIL FOREIGN KEY(THUMNAIL_ID) REFERENCES IMAGE(ID);

DROP TABLE COLLECTION_IMAGES CASCADE CONSTRAINTS;
CREATE TABLE COLLECTION_IMAGES(
    ID NUMBER           PRIMARY KEY,
    COLLECTION_ID       NUMBER          NOT NULL,
    IMAGE_ID            VARCHAR2(32)    NOT NULL
);
ALTER TABLE COLLECTION_IMAGES ADD CONSTRAINT FK_COLLECTION FOREIGN KEY(COLLECTION_ID) REFERENCES COLLECTION(ID);
ALTER TABLE COLLECTION_IMAGES ADD CONSTRAINT FK_COLLECTION_IMAGE FOREIGN KEY(IMAGE_ID) REFERENCES IMAGE(ID);

DROP SEQUENCE NEWS_SEQ;
CREATE SEQUENCE NEWS_SEQ
    INCREMENT BY 1
    START WITH 1;

DROP TABLE NEWS CASCADE CONSTRAINTS;
CREATE TABLE NEWS(
    ID             NUMBER         PRIMARY KEY,
    TITLE          VARCHAR2(100)  NOT NULL,
    CONTENT        VARCHAR2(4000) NOT NULL,
    IMAGE_ID       VARCHAR2(32)   NOT NULL,
    THUMNAIL_ID    VARCHAR2(32)   NOT NULL
);
ALTER TABLE NEWS ADD CONSTRAINT FK_NEWS_IMAGE FOREIGN KEY(IMAGE_ID) REFERENCES IMAGE(ID);
ALTER TABLE NEWS ADD CONSTRAINT FK_NEWS_THUMNAIL FOREIGN KEY(THUMNAIL_ID) REFERENCES IMAGE(ID);



----

DROP SEQUENCE MEMBER_SEQ;
CREATE SEQUENCE MEMBER_SEQ
       INCREMENT BY 1
       START WITH 1;

DROP TABLE MEMBER CASCADE CONSTRAINTS;
CREATE TABLE MEMBER(
    ID VARCHAR2(50)   PRIMARY KEY, -- 멤버아이디
    NAME VARCHAR2(50) NOT NULL,    -- 멤버 이름
    TEL VARCHAR2(50)  NOT NULL,    -- 멤버 전화번호
    PWD VARCHAR2(400) NOT NULL     -- 멤버 비밀번호 
);

DROP SEQUENCE BOARD_SEQ;
CREATE SEQUENCE BOARD_SEQ
       INCREMENT BY 1
       START WITH 1;

DROP TABLE BOARD CASCADE CONSTRAINTS;
CREATE TABLE BOARD(
    NO          NUMBER(10) PRIMARY KEY,  -- 글 번호(PK)
    TITLE       VARCHAR2(500) NOT NULL,  -- 글 제목
    CONTENT     VARCHAR2(5000) NOT NULL, -- 글 내용
    REGDATE     DATE,                    -- 글 작성일
    VIEWCNT     NUMBER(10) DEFAULT 0,    -- 글 조회수
    MEMBER_ID   VARCHAR2(50)             -- 글 작성자(FK)
);

ALTER TABLE BOARD ADD CONSTRAINT FK_MNO FOREIGN KEY(MEMBER_ID) REFERENCES MEMBER(ID);

---

DROP SEQUENCE DISCLOSURE_SEQ;
CREATE SEQUENCE DISCLOSURE_SEQ
        INCREMENT BY 1
        START WITH 1;

DROP TABLE DISCLOSURE CASCADE CONSTRAINTS;
CREATE TABLE DISCLOSURE(
    DISCLOSURE_ID   NUMBER(10) PRIMARY KEY,
    DISCLOSURE_NAME VARCHAR2(100) NOT NULL,
    PRESENTER       VARCHAR2(100) NOT NULL,
    INDATE          DATE          NOT NULL
);

---

DROP SEQUENCE mall_type_seq;
-- mall_type 테이블 id sequence
CREATE SEQUENCE mall_type_seq INCREMENT BY 1 START WITH 1;

DROP SEQUENCE brand_type_seq;
-- brand_type 테이블 id sequence
CREATE SEQUENCE brand_type_seq INCREMENT BY 1 START WITH 1;

DROP SEQUENCE brand_seq;
-- brand 테이블 id sequence
CREATE SEQUENCE brand_seq INCREMENT BY 1 START WITH 1;

DROP TABLE mall_type CASCADE CONSTRAINTS;
-- 쇼핑몰 분류 테이블
CREATE TABLE mall_type (
    id   NUMBER
        CONSTRAINT mall_type_id_pk PRIMARY KEY,
    name VARCHAR2(100)
        CONSTRAINT mall_type_uri_uk UNIQUE
        CONSTRAINT mall_type_uri_nn NOT NULL
);

DROP TABLE brand_type CASCADE CONSTRAINTS;
-- 브랜드 분류 테이블
CREATE TABLE brand_type (
    id   NUMBER(4)
        CONSTRAINT brand_type_id_pk PRIMARY KEY,
    name VARCHAR2(100)
        CONSTRAINT brand_type_name_uk UNIQUE
        CONSTRAINT brand_type_name_nn NOT NULL
);

DROP TABLE brand CASCADE CONSTRAINTS;
-- 브랜드 정보 테이블
-- id, 분류, 이름, 키워드, 설명, 쇼핑몰 분류, 쇼핑몰 브랜드 id
CREATE TABLE brand (
    id          NUMBER(4)
        CONSTRAINT brand_id_pk PRIMARY KEY,
    type        NUMBER(4)
        CONSTRAINT brand_type_nn NOT NULL,
    name        VARCHAR2(100)
        CONSTRAINT brand_name_uk UNIQUE
        CONSTRAINT brand_name_nn NOT NULL,
    ss          VARCHAR2(100),
    description VARCHAR2(4000),
    mall_type   NUMBER,
    mall_id     VARCHAR2(10),
    CONSTRAINT brand_type_fk FOREIGN KEY ( type )
        REFERENCES brand_type ( id ),
    CONSTRAINT mall_type_fk FOREIGN KEY ( mall_type )
        REFERENCES mall_type ( id )
);

DROP TABLE brand_img CASCADE CONSTRAINTS;
-- 브랜드 이미지 파일 정보
-- 브랜드 id, 파일 URI
CREATE TABLE brand_img (
    id       NUMBER(6)
        CONSTRAINT brand_img_id_pk PRIMARY KEY,
    brand_id NUMBER(4),
    uri      VARCHAR2(2000),
    CONSTRAINT brand_img_brand_id_fk FOREIGN KEY ( brand_id )
        REFERENCES brand ( id )
);